on: [push]

name: ARM v7 check
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Update Rust
        run: rustup update
        
      - name: Install cargo cross
        run: cargo install cross

      - name: Cross-compile arm
        run: cross check --target armv7-unknown-linux-gnueabihf --no-default-features

      - name: Check output
        run: ls target/

